config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "users" => redirect("/users/sign_up")
  # ゲストログイン
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get '/about' => 'homes#about', as: 'about'

  resources :users, only: [:show, :edit, :update] do
    # いいねした投稿一覧
    member do
      get :favorites
    end
  end

  namespace :admin do
    resources :users, only: [:index, :destroy]
  end

  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]

    collection do
      get 'confirm' #下書き
      get 'search'
      get 'search_tag'
    end

  end

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  
  def create
    @post = Post.find(params[:post_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.post_id = @post.id
    flash[:notice] = if comment.save
                       'コメントの投稿に成功しました！'
                     else
                       'コメントの投稿に失敗しました。'
                     end
    redirect_to post_path(@post)
  end

  def destroy
    PostComment.find(params[:id]).destroy
    @post = Post.find(params[:post_id])
    render :post_comments
  end

  private

    def post_comment_params
      params.require(:post_comment).permit(:comment)
    end
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/views/post_comments/_comments.html.erb
<!--コメント一覧-->
<div class=" align-items-end">
  <p><i class="fas fa-comment-alt"></i>コメント件数：<%= post.post_comments.count %></p>
  <% if user_signed_in? %>
  <!--ログインしていたらコメント表示-->
    <% post.post_comments.each do |post_comment| %>
      <div class="row d-flex align-items-center">
        <%= image_tag post_comment.user.get_profile_image, size: "50x50", class: "mr-2 rounded-circle user-icon" %>
        <%= link_to post_comment.user.name, user_path(post_comment.user), class: "mr-2" %>
        <div class="mr-2">
          <%= post_comment.comment %>
        </div>
        
        <% if post_comment.user.id == current_user.id %>
        <!--コメント投稿者の場合の削除ボタン-->
          <%= link_to "コメント削除", post_post_comment_path(post_comment.post, post_comment), method: :delete, remote: true, class: "btn btn-sm btn-outline-danger" %><br>
          
        <% elsif current_user == @user || current_user.admin? %>
        <!--管理者の場合の削除ボタン-->
          <%= link_to "コメント削除(管理者用）", post_post_comment_path(post_comment.post, post_comment), method: :delete, remote: true, class: "btn btn-sm btn-outline-warning" %><br>
        <% end %>
      
      </div>
    <% end %>
    
  <% end %>
</div>

app/views/post_comments/_form.html.erb
 <!--コメントフォーム（ログインしていたら表示）-->
<% if user_signed_in? %>
  <%= form_with model: [post, post_comment], local: false do |f| %>
    <%= f.text_area :comment, rows: '4', placeholder: "ここにコメントを書いてください", class: "w-100 text-area" %>
    <%= f.submit "コメント送信" %>
  <% end %>
<% end %>

app/views/post_comments/post_comments.js.erb
<!--id="comments_areaにをrenderで指定した部分テンプレートに更新-->
$("#comments_area").html("<%= j(render 'post_comments/comments', post: @post ) %>");

<!--フォームを送信したあとにフォームの値を空にします-->
$("textarea").val('');