config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "users" => redirect("/users/sign_up")
  # ゲストログイン
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get '/about' => 'homes#about', as: 'about'

  resources :users, only: [:show, :edit, :update] do
    # いいねした投稿一覧
    member do
      get :favorites
    end
  end

  namespace :admin do
    resources :users, only: [:index, :destroy]
  end

  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]

    collection do
      get 'confirm' #下書き
      get 'search'
      get 'search_tag'
    end

  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :encrypted_password, presence: true, uniqueness: true

   # プロフィール画像
  has_one_attached :profile_image

  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_profile_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image
  end

  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = 'guestuser'
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end


  # ログイン時に退会済みのユーザーが同じアカウントでログイン出来ないよう制約
  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  # 管理ユーザー以外で特定のアクションを実行しようとした場合には、トップページにリダイレクトさせる
  before_action :if_not_admin
  
  def index
    @users = User.all
  end
  
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path, notice: "ユーザーが削除されました。"
  end
  
  
private

  def user_params
    params.require(:user).permit(:name, :profile_image, :email, :introduction)
  end
  
  def if_not_admin
    redirect_to root_path unless current_user.admin?
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: "guestuserでログインしました。"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # 各アクションを実行する前に実行したい処理を指定(before_action)
  before_action :is_matching_login_user, only: [:edit, :update]
  before_action :set_user, only: [:favorites]
  before_action :ensure_guest_user, only: [:edit]


  def show
    @user = User.find(params[:id])
    @posts = @user.posts.published
    @posts_page = @user.posts.published.page(params[:page]).per(8)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  # いいねした投稿一覧
  def favorites
    favorites = Favorite.where(user_id: @user.id).pluck(:post_id)
    @favorite_posts = Post.find(favorites) #いいねした投稿
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :email, :introduction)
  end

  def user_admin
    @users = User.all
    if  current_user.admin == false
        redirect_to root_path
    else
        render action: "index"
    end
  end

  def set_user
    @user = User.find(params[:id])
  end


  # 他のユーザーからのアクセス制限(is_matching_login_userというメソッドにまとめる)
  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to posts_path
    end
  end

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.guest_user?
      redirect_to user_path(current_user) , notice: "ゲストユーザーはプロフィール編集画面へ遷移できません。"
    end
  end  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <div class="mt-4">
    <h3 class="font-weight-bold">マイページ編集</h3>
    <!--エラーメッセージ-->
    <% if @user.errors.any? %>
      <%= @user.errors.count %>件のエラーが発生しました
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    <!--編集フォーム-->
    <div class="mt-5">

      <%= form_with model: @user, url: user_path, method: :patch, local:true do |f| %>
        <div class="field row my-4">
          <label class="col-3">プロフィール画像</label>
            <%= image_tag @user.get_profile_image, size: "200x200", class: "user-icon" %>
            <div class="d-flex align-items-end">
              <%= f.file_field :profile_image, placeholder: "アイコン画像", accept: "image/*" %>
            </div>
        </div>
        <div class="field row mt-2">
          <label class="col-3">ユーザー名</label>
            <%= f.text_field :name, autofocus: true, autocomplete: "name", class: "col-7 form-control" %>
        </div>

        <div class="field row mt-2">
          <label class="col-3">自己紹介</label>
            <%= f.text_area :introduction, class: "col-7 form-control", rows: "4", placeholder: "例）コーヒー大好き" %>
        </div>

        <div class="field row mt-2">
          <label class="col-3">メールアドレス</label>
            <%= f.email_field :email, autocomplete: "email", class: "col-7 form-control" %>
        </div>

       <!--編集内容を保存ボタン-->
        <div class="action row mt-3">
          <div class="col-3"></div>
          <div>
            <%= f.submit "編集内容を保存",class: "btn btn-sm btn-success px-5 font-weight-bold" %>
          </div>
        </div>
      <% end %>
    </div>
    <!--退会ボタン-->
    <div class="actions row mt-5">
      <div class="col-7"></div>
      <div>
        <%#= link_to "退会する", customers_confirm_withdraw_path, class: "btn btn-sm btn-danger px-5" %>
      </div>
    </div>

  </div>
</div>

app/views/users/favorites.html.erb
<div class="container  mt-5 pb-5">
  <div class="col-md-12">
    <h2 class="mb-3 ml-5 text-center">いいね❤️した投稿一覧</h2>

      <div class="row">
        <%= render 'posts/post', posts: @favorite_posts %>
      </div>

  </div>
</div>

app/views/users/show.html.erb
<!-- ユーザーの詳細 -->
<%= stylesheet_link_tag "users", :media => "all" %>
<div class="container">
<div class="mt-4">
  
    <h3 class="font-weight-bold">マイページ</h3>
    <!--本人だったら-->
    <% if @user.id == current_user.id %>
      <div class="mt-4">
        <span class="font-weight-bold">登録情報</span>
        <!--ユーザーのemailがguest@example.comではない場合には、ボタンを表示-->
        <% unless @user.guest_user? %>
          <%= link_to "編集する", edit_user_path(@user), class: "pull-right btn  btn-sm btn-outline-secondary col-2 mx-3 font-weight-bold"  %>
        <% end %>
        <%= link_to "いいねした投稿", favorites_user_path(@user), class: "pull-right btn  btn-sm btn-outline-info col-2 mx-3 font-weight-bold" %>
        <%= link_to "非公開中の投稿", confirm_posts_path(@user), class: "pull-right btn  btn-sm btn-outline-warning col-2 mx-3 font-weight-bold" %>
      </div>


      <div class="row">
        <%= image_tag @user.get_profile_image, size: "200x200", class: "user-icon mt-3" %>
      <!--登録情報テーブル-->
      <table class="teble table-bordered px-2 col-8 mt-3 ml-5">
        <tr>
          <th class="col-3 table-active py-2">ユーザー名</th>
          <td class="pl-3"><%= @user.name %></td>
        </tr>
        <tr>
          <th class="col-3 table-active py-2">自己紹介</th>
          <td class="pl-3"><%= @user.introduction %></td>
        </tr>
        <tr>
          <th class="col-3 table-active py-2">メールアドレス</th>
          <td class="pl-3"><%= @user.email %></td>
        </tr>
        <!--<tr>-->
        <!--  <th class="col-3 table-active py-2">パスワード</th>-->
        <!--  <td class="pl-3"><%#= @user.encrypted_password %></td>-->
        <!--</tr>-->
      </table>
      </div>
    <% else %>
    <div class="row">
      <%= image_tag @user.get_profile_image, size: "200x200", class: "user-icon mt-3" %>
      <table class="teble table-bordered px-2 col-7 mt-3 ml-5">
        <tr>
          <th class="col-3 table-active py-2">ユーザー名</th>
          <td class="pl-3"><%= @user.name %></td>
        </tr>
        <tr>
          <th class="col-3 table-active py-2">自己紹介</th>
          <td class="pl-3"><%= @user.introduction %></td>
        </tr>
      </table>
    </div>
    <% end %>
    <!-- ユーザーの投稿一覧 -->
    <h3 class="font-weight-bold mt-5">投稿一覧</h3>
    <div class="row">
      <%= render 'posts/post', posts: @posts_page, user: @user %>
    </div>
    <div class="justify-content-center">
      <%= paginate @posts_page %>
    </div>

</div>
</div>