config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "users" => redirect("/users/sign_up")
  # ゲストログイン
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get '/about' => 'homes#about', as: 'about'

  resources :users, only: [:show, :edit, :update] do
    # いいねした投稿一覧
    member do
      get :favorites
    end
  end

  namespace :admin do
    resources :users, only: [:index, :destroy]
  end

  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]

    collection do
      get 'confirm' #下書き
      get 'search'
      get 'search_tag'
    end

  end

end

app/models/post.rb
class Post < ApplicationRecord

  # アソシエーション
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # いいね機能でのユーザーの存在
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

# enum
  # 曜日選択         {日曜: 0、月曜: 1、火曜: 2、水曜: 3、木曜: 4、金曜: 5、土曜: 6、祝日: 7}
  enum stay_weekday: { sunday: 0, monday: 1, tuesday: 2, wednesday: 3, thursday: 4, friday: 5, saturday: 6, holiday: 7 }
  WEEKDAY = {
    '日曜' => 'sunday',
    '月曜' => 'monday',
    '火曜' => 'tuesday',
    '水曜' => 'wednesday',
    '木曜' => 'thursday',
    '金曜' => 'friday',
    '土曜' => 'saturday',
    '祝日' => 'holiday',
  }
  # 混み具合選択          {空いている: 0、半分くらい: 1、ほぼ満席: 2、待っている人も居た: 3}
  enum congestion_degree: { empty: 0, half: 1, full: 2, over: 3 }
  # 下書き機能.     {投稿する: 0、下書きする: 1 }
  enum save_status: { published: 0, draft: 1 }

  # 複数画像投稿
  has_many_attached :images

  # 投稿画像について
  def get_images
    unless images.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      images.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      images
  end

  # タグのリレーションのみ記載
  has_many :post_shop_tags, dependent: :destroy
  has_many :shop_tags, through: :post_shop_tags, dependent: :destroy

  def save_shop_tags(tags)
  # タグが存在していれば、タグの名前を配列として全て取得
    current_tags = self.shop_tags.pluck(:name) unless self.shop_tags.nil?
    # 現在取得したタグから送られてきたタグを除いてoldtagとする
    old_tags = current_tags - tags
    # 送信されてきたタグから現在存在するタグを除いたタグをnewとする
    new_tags = tags - current_tags
    # 古いタグを消す
    old_tags.each do |old_name|
      self.shop_tags.delete ShopTag.find_by(name:old_name)
    end
    # 新しいタグを保存
    new_tags.each do |new_name|
      shop_tag = ShopTag.find_or_create_by(name:new_name)
      self.shop_tags << shop_tag
    end
  end

  # キーワード、タグ検索
  scope :search_by_keywords, ->(keywords) {
    keywords_array = keywords.split(/\s+/) # キーワードをスペースで分割して配列化
    weekday = WEEKDAY.filter_map { |key, value| value if keywords_array.first.include?(key) }.first

    self.joins(:post_shop_tags).joins(:shop_tags).joins(:user).where(
      keywords_array.map { |_|
        [
          'shop_name LIKE :keyword',
          'shop_introduction LIKE :keyword',
          'shop_postal_code LIKE :keyword',
          'shop_address LIKE :keyword',
          'stay_weekday LIKE :keyword', # enum の場合、値の一致を確認
          'stay_time_start LIKE :keyword',
          'stay_time_end LIKE :keyword',
          'congestion_degree LIKE :keyword', # enum の場合、値の一致を確認
          'shop_tags.name LIKE :keyword',#shop_tagsテーブルのnameカラム
          'users.name LIKE :keyword' #usersテーブルのnameカラム
        ].join(' OR ')
      }.join(' OR '),
      *keywords_array.map do |keyword| { keyword: "%#{keyword}%" }
      end
    ).or(self.where(stay_weekday: weekday)).uniq  #投稿が重複しないように
  }

  # バリデーション
  with_options presence: true do
    validates :shop_name
    validates :shop_introduction
    validates :shop_postal_code
    validates :shop_address
    validates :stay_weekday
    validates :stay_time_start
    validates :stay_time_end
    validates :congestion_degree
  end

  validates :images, length: { maximum: 4, message: "は4枚までしかアップロードできません" }

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
   before_action :authenticate_user!, except: [:index, :show]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    @post.user_id = current_user.id
     # 受け取った値を,で区切って配列にする
    @shop_tags = params[:post][:name].split(',')

    if @post.save
      @post.save_shop_tags(@shop_tags)
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  # 下書き
  def confirm
    @posts = current_user.posts.draft.all
  end

  def index
    @posts = Post.published.all # 公開済み（published）」のすべての投稿を取得
    @posts_page = Post.published.all.page(params[:page]).per(8)
  # 全てのタグを取得
    ShopTag.all.each do |shop_tag|
       # 投稿が0件のタグを削除
      shop_tag.destroy if shop_tag.post_shop_tags.size == 0
    end
    # 0件のを削除後のタグ全て取得
    @shop_tags = ShopTag.all
  end

  def show
    @post = Post.find(params[:id])
    @shop_tags = @post.shop_tags.pluck(:name).join(',')
    @post_shop_tags = @post.shop_tags
    @post_comment = PostComment.new
  end

  def edit
    @post = Post.find(params[:id])
    @shop_tags = @post.shop_tags.pluck(:name).join(',')
  end

  def update
    @post = Post.find(params[:id])

    shop_tags = params[:post][:name].split(',')
    #添付画像を個別に削除
    if params[:post][:image_ids]
      params[:post][:image_ids].each do |image_id|
        image = @post.images.find(image_id)
        image.purge
      end
    end

    if @post.update(post_params)
       @post.save_shop_tags(shop_tags)
      flash[:notice] = "変更に成功しました！"
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "投稿が削除されました。"
    redirect_to root_path
  end

  # タグ
  def search_tag
    # 検索結果画面でもタグ一覧表示
     @shop_tags = ShopTag.all
    #検索されたタグを受け取る
     @search_shop_tag = ShopTag.find(params[:shop_tag_id])
    #検索されたタグに紐づく投稿を表示
     @shop_tag_post_results = @search_shop_tag.posts.published
  end

  # 検索機能（キーワード、タグ）
  def search
    @keywords = params[:keywords] #検索ワードを格納
    @search_results = Post.published.search_by_keywords(@keywords)#公開済み（published）」のすべての投稿を検索結果を格納
  end

  # 投稿データのストロングパラメータ
  private

  def post_params
    params.require(:post).permit(:shop_name, :shop_introduction, :shop_postal_code, :shop_address, :stay_weekday, :stay_time_start, :stay_time_end,
                                 :congestion_degree, :admin, :save_status, images: [])
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with model: post, local: true do |f| %>
      <div class="form-group row mt-5">
        <!--保存されている画像があったら(編集の時）-->
        <% if post.images.attached? %>
          <div>
            <p>選択済みの画像（削除する画像にチェックをつけてください）</p>
          </div>

          <div style="display: flex; flex-wrap: wrap; width: 750px;">
            <% post.images.each do |image| %>
              <div style="display: flex; margin:5px 5px 5px 0;">
                <%= f.check_box :image_ids, { multiple: true }, image.id, false %>
                <label form="user_image_ids_<%= image.id %>" >
                  <%= image_tag image, size: '300x200' %>
                </label>
              </div>
             <% end %>
          </div>

        <% end %>
        <!--画像登録-->
        <%= f.label :images, "投稿する画像（4枚まで投稿可）", class: "col-4 col-form-label" %>
        <%= f.file_field :images, accept: "image/*", multiple: true, class: "image-item" %>
      </div>

      <!--店名-->
      <div class="row form-group">
        <%= f.label :shop_name, "お店の名前", class: "col-4 col-form-label" %>
        <%= f.text_field :shop_name, class: "col-7 form-control", placeholder: "例）○○店" %>
      </div>

      <!--紹介文-->
      <div class="row form-group">
        <%= f.label :shop_introduction, "お店の紹介文", class: "col-4 col-form-label" %>
        <%= f.text_area :shop_introduction, class: "col-7 form-control", rows: "4", placeholder: "例）レトロな雰囲気で、ゆったりとした時間を過ごせます！" %>
      </div>

      <!--タグ-->
      <div class="row form-group">
        <%= f.label :name, "タグ(,で区切ると複数登録できます)", class: "col-4 col-form-label" %>
        <%= f.text_field :name,value: shop_tags, class: 'col-7 form-control', placeholder: "例）レトロ,コーヒーが美味しい" %>
      </div>

      <!--住所自動入力-->
      <div class="h-adr">
        <span class="p-country-name" style="display:none;">Japan</span>
        <!--店の郵便番号-->
        <div class="row form-group">
          <%= f.label :shop_postal_code, "お店の郵便番号(ハイフンなし）", class: "col-4 col-form-label" %>
          〒<%= f.text_field :shop_postal_code, class: 'p-postal-code col-2 form-contro', placeholder: "例）0123456", size: "8", maxlength: "8" %>
        </div>

        <!--店の住所-->
        <div class="form-group row">
          <%= f.label :shop_address, "お店の住所", class: "col-4 col-form-label" %>
          <%= f.text_field :shop_address, class: 'p-region p-locality p-street-address p-extended-address col-7 form-control', placeholder: "例）鹿児島県鹿児島市〇〇-〇〇" %>
        </div>
      </div>

      <!--曜日選択-->
      <div class="form-group row">
        <%= f.label :stay_weekday, "お店を利用した曜日", class: "col-4 col-form-label" %>
        <%= f.select :stay_weekday, Post.stay_weekdays_i18n.invert,{class: "form-select", include_blank: "選択してください"} %>
      </div>

      <!--時間帯-->
      <div class="form-group row">
        <%= f.label :stay_time, "お店を利用した時間帯", class: "col-4 col-form-label" %>
        <%= f.select :stay_time_start, *[1..24], {:prompt => "時間選択"}, class:"mr-1" %> 時頃〜
        <%= f.select :stay_time_end, *[1..24], {:prompt => "時間選択"}, class:"mx-1" %> 時頃に利用した
      </div>

      <!--混み具合選択-->
      <div class="form-group row">
        <%= f.label :congestion_degree, "お店の混み具合", class: "col-4 col-form-label" %>
        <%= f.select :congestion_degree, Post.congestion_degrees_i18n.invert,{class: "form-select", required: true, include_blank: "選択してください"} %>
      </div>

      <div class="form-group row" >
        <%= f.label :save_status, "公開・非公開", class: "col-4 col-form-label" %>
        <%= f.select :save_status, Post.save_statuses.keys.map { |k| [t("enums.post.save_status.#{k}"),k]}, {}, {class: "form-select"} %>
      </div>

    <div class="form-group text-center">
      <% if request.path_info == new_post_path %>
        <%= f.submit "送信する", class: "btn btn-outline-primary px-4 py-2" %>
      <% else %>
        <%= f.submit "変更を保存", class: "btn btn-outline-success px-4 py-2" %>
      <% end %>
    </div>

<% end %>

app/views/posts/_post.html.erb
<% posts.each do |post| %>
  <div class="col-3">
    <!--投稿者-->
    <div class="mt-1">
      <%= link_to user_path(post.user.id) do %>
        <%= image_tag post.user.get_profile_image, size: "50x50", class: "mb-2 rounded-circle user-icon" %>
      
        <%= post.user.name %>
      
      <% end %>
    </div>
    <!--投稿内容-->
    <%= link_to post_path(post.id) ,style: "color: black;" do %>
      <% if post.images.attached? %>
        <%= image_tag post.images[0], class: "rounded",size:"150x100", class: "rounded-bottom" %>
      <% else %>
        <%= image_tag('no_image.jpg', size: '150x100') %>
      <% end %>
      <p><%= post.shop_name %></p>
      <p><i class="fas fa-map-marker-alt"></i><%= post.shop_address %></p>
      <p id="favorite_buttons_<%= post.id %>" >
        <%= render "favorites/favorite", post: post %>
      </p>
      <p><i class="far fa-comment-dots"></i></i><%= post.post_comments.count %></p>
    <% end %>

  </div>
<% end %>

app/views/posts/_sidebar_tags.html.erb
<!--ジャンル検索サイドバー-->
<table class="tag-table" >

  <thead class="tag-table-title1">
    <tr>
      <th class="tag-table-title2 pb-2">タグ一覧</th>
    </tr>
  </thead>

  <tbody>
  <% shop_tags.each do |shop_tag|%>
    <tr>
      <td class="tag-table-item pb-2">
        <i class="fa-sharp fa-solid fa-tag"></i>
        <%= link_to shop_tag.name,search_tag_posts_path(shop_tag_id: shop_tag.id) %>
        <%="(#{shop_tag.posts.count})" %>
      </td>
    </tr>
  <% end %>
  </tbody>

</table>

app/views/posts/confirm.html.erb
<div class="container  mt-5 pb-5">
  <div class="col-md-12">
    <h2 class="mb-3 ml-5 text-center font-weight-bold">非公開中の投稿一覧</h2>

      <div class="row">
        <%= render 'post', posts: @posts %>
      </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="container mt-5 pb-5">
  <div class="text-center">
    <h2 class="mb-3 ml-5 font-weight-bold">投稿内容の編集</h2>
    <div class="row">
      <div class="col-12">
        <%= render 'layouts/errors', obj: @post %>
      </div>
    </div>
    <div class="form-group">
      <%= render 'form', post: @post, shop_tags: @shop_tags %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container  pb-5">
  <div class="row pt-5">
    <!--タグ一覧-->
    <div class="col-md-3 mt-3">
      <%= render "sidebar_tags", shop_tags: @shop_tags %>
    </div>


  <div class="col-md-9">
    <h2 class="mb-3 text-center font-weight-bold">投稿の一覧</h2>
      <div class="row">
        <%= render 'post', posts: @posts_page %>
      </div>
      <div class="justify-content-center">
        <%= paginate @posts_page %>
      </div>
  </div>

  </div>
</div>

app/views/posts/new.html.erb
<div class="container mt-5 pb-5">
  <div class="text-center">
  <h2 class="mb-3 ml-5 font-weight-bold">新規投稿</h2>

    <div class="row">
      <div class="col-12">
        <%= render 'layouts/errors', obj: @post %>
      </div>
    </div>

    <div class="form-group">
      <%= render 'form', post: @post, shop_tags: @shop_tags %>
    </div>

  </div>
</div>

app/views/posts/search.html.erb
<div class="container  mt-5 pb-5">
  <div class="col-md-12">
    <h2 class="mb-3 ml-5 text-center font-weight-bold">「<%= @keywords %>」の検索結果</h2>
      <% if @search_results.present? %>
      <!--キーワード結果の値があったら-->
        <div class="row">
          <%= render 'post', posts: @search_results %>
        </div>

      <% else %>
      <!--結果の値がなかったら-->
        <p>一致する情報は見つかりませんでした</p>
      <% end %>
  </div>
</div>

app/views/posts/search_tag.html.erb
<div class="container  mt-5 pb-5">
  <div class="col-md-12">
    <h2 class="mb-3 ml-5 text-center font-weight-bold">タグが「<%= @search_shop_tag.name %>」の投稿一覧</h2>
    <p class="mb-3 ml-5 text-center font-weight-bold">
      <i class="fas fa-exclamation-triangle"></i>
      非公開中の投稿は表示されません
    </p>
    <% if @shop_tag_post_results.present? %>
      <div class="row">
        <%= render 'post', posts: @shop_tag_post_results %>
      </div>
    <% else %>
      <p class="mt-5 ml-5 text-center">一致する情報は見つかりませんでした</p>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container mt-5 pb-5">
  <div class="form-group">

    <h2 class="mb-3 ml-5 text-center font-weight-bold">投稿の内容</h2>

    <div class="row mt-5 mb-5">

      <div class="col-lg-7">
        <% if @post.images.attached? %>
          <% @post.images.each do |image| %>
            <%= image_tag image.variant(resize: '300x250'), style: "object-fit: cover;", class: "post-item" %>
          <% end %>
        <% else %>
          <%= image_tag('no_image.jpg', size: '300x250') %>
        <% end %>

        <div id="favorite_buttons_<%= @post.id %>" >
          <%= render "favorites/favorite", post: @post %>
        </div>

        <div class="pt-3">
          <%= link_to user_path(@post.user.id) ,style: "color: black;" do %>
            <p>このお店を紹介した人
      　     <%= image_tag @post.user.get_profile_image, size: "50x50", class: "rounded-circle user-icon"; %>
              <%= @post.user.name %>
            </p>
          <% end %>
        </div>
      </div>

      <div class="col-lg-5 ">
        <table class="table mx-auto">
          <tbody>
            <tr>
              <td>お店の名前</td>
              <td><%= @post.shop_name %></td>
            </tr>

            <tr>
              <td>お店の紹介文</td>
              <td><%= @post.shop_introduction %></td>
            </tr>

            <tr>
              <td>タグ</td>
              <td>
                <% @post_shop_tags.each do |shop_tag| %>
                  <i class="fa-sharp fa-solid fa-tag"></i>
                  <%= link_to shop_tag.name,search_tag_posts_path(shop_tag_id: shop_tag.id) %>
                <% end %>
               </td>
            </tr>

            <tr>
              <td>お店の郵便番号</td>
              <td><%= @post.shop_postal_code %></td>
            </tr>

            <tr>
              <td>お店の住所</td>
              <td><%= @post.shop_address %></td>
            </tr>

            <tr>
              <td>お店を利用した曜日</td>
              <td><%= @post.stay_weekday_i18n %></td>
            </tr>

            <tr>
              <td>お店を利用した時間帯</td>
              <td><%= @post.stay_time_start %>時〜<%= @post.stay_time_end %>時ごろ</td>
            </tr>

            <tr>
              <td>お店の混み具合</td>
              <td><%= @post.congestion_degree_i18n %></td>
            </tr>

            <tr>
              <td>公開・非公開</td>
              <td><%= @post.save_status_i18n %></td>
            </tr>

          </tbody>
        </table>
      </div>

    </div>

    <!--ボタン-->
    <div>
        <!--投稿者本人だったら-->
        <% if @post.user == current_user %>
          <div class="text-center">
            <%= link_to "編集する", edit_post_path, class: "btn btn-outline-success mt-3 ml-5 px-4 py-2" %>
            <%= link_to "削除する", post_path(@post), method: :delete, class: "btn btn-outline-danger mt-3 ml-5 px-4 py-2" %>
          </div>

        <!--管理者だったら-->
        <% elsif current_user&.admin? %>
          <div class="text-center">
            <%= link_to "投稿削除(管理者用）", post_path(@post), method: :delete, class: "btn btn-outline-warning mt-3 ml-5 px-4 py-2" %>
          </div>
        <% end %>
      <%# end %>
    </div>

    <!--コメント一覧-->
    <div id="comments_area">
      <%= render 'post_comments/comments', post: @post %>
    </div>
    <!--コメントフォーム-->
    <div class="mt-3">
      <%= render "post_comments/form", post: @post, post_comment: @post_comment %>
    </div>

  </div>
</div>