config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "users" => redirect("/users/sign_up")
  # ゲストログイン
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get '/about' => 'homes#about', as: 'about'

  resources :users, only: [:show, :edit, :update] do
    # いいねした投稿一覧
    member do
      get :favorites
    end
  end

  namespace :admin do
    resources :users, only: [:index, :destroy]
  end

  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]

    collection do
      get 'confirm' #下書き
      get 'search'
      get 'search_tag'
    end

  end

end

app/views/layouts/_errors.html.erb
<%= stylesheet_link_tag "posts", :media => "all" %>
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= t("errors.template.header", model: Post.model_name.human, count: obj.errors.count) %></h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= t message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg shadow">
    <div class="container mx-auto">
      <a class="navbar-brand " href="/"><%= image_tag('logo.png', size: '150x120') %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto row">
        <!--ログイン表記-->
        <div class="login-name mx-auto text-success">
          <% if user_signed_in? && current_user.admin? %>
            <p>管理者ログイン中</p>
          <% elsif user_signed_in? %>
            <p>ようこそ <%= current_user.name %>さん！</p>
          <% end %>
        </div>

        <ul class="nav navbar-nav">
          <% if user_signed_in? %><!--ユーザーがログインしているとき-->
          <li>
            <%= link_to about_path,class: 'nav-link text-secondary' do %>
              <i class="fas fa-exclamation-circle"></i>
              About
            <% end %>
          </li>

          <li>
            <%= link_to new_post_path, class: 'nav-link text-secondary',data: {"turbolinks"=>false} do %>
            <!--turbolinksを適用させない-->
              <i class="fas fa-paper-plane"></i>
              投稿する
            <% end %>
          </li>
          <li>
            <%= link_to posts_path, class: 'nav-link text-secondary' do %>
              <i class="fas fa-list-ul"></i>
              投稿一覧
            <% end %>
          </li>
          <li>
            <%= link_to user_path(current_user), class: 'nav-link text-secondary' do %>
              <i class="fas fa-user-circle"></i>
              マイページ
            <% end %>
          </li>

          <li>
            <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-secondary' do %>
              <i class="fas fa-sign-out-alt"></i>
              ログアウト
            <% end %>
          </li>

          <li class="ml-3">
            <%= render 'layouts/search_form' %>
          </li>

           <% else %>  <!--ログインしていないとき-->

          <li>
            <%= link_to about_path,class: 'nav-link text-secondary' do %>
              <i class="fas fa-exclamation-circle"></i>
               About
            <% end %>
          </li>

          <li>
            <%= link_to new_user_registration_path,class: 'nav-link text-secondary' do %>
              <i class="fas fa-user-plus"></i>
               新規登録
            <% end %>
          </li>

          <li>
            <%= link_to new_user_session_path ,class: 'nav-link text-secondary' do %>
              <i class="fas fa-sign-in-alt"></i>
              ログイン
            <% end %>
          </li>

          <li>
            <%= link_to users_guest_sign_in_path, class: "nav-link text-secondary sign_in", method: :post do %>
              <i class="fa-solid fa-user-tie"></i>
              ゲストログイン<br>（ 閲覧用 ）
            <% end %>
          </li>

          <li class="ml-3">
            <%= render 'layouts/search_form' %>
          </li>

        <% end %>
        </ul>
      </ul>
    </div>
    </div>
  </nav>
</header>

app/views/layouts/_search_form.html.erb
<!--検索窓-->
<%= form_tag search_posts_path, method: :get do %>
  <%= text_field_tag :keywords, params[:keywords], placeholder: "例）店舗名、タグ...", required: true %>
  <%= submit_tag "検索"%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>鹿児島ひとり時間</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/0c41007c71.js" crossorigin="anonymous"></script>
    <script src="https://yubinbango.github.io/yubinbango/yubinbango.js" charset="UTF-8"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Zen+Kurenaido&family=Zen+Maru+Gothic&display=swap" rel="stylesheet">
    <%= favicon_link_tag 'favicon.ico' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main class="pb-5">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>

   <footer class="bg-secondary text-white pt-3 pb-2">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-4 mt-3">
            <p>鹿児島ひとり時間</p>
          </div>
          <div class="col-md-8">
            <ul class="p-0 list-unstyled row">
              <div class="col-3">
              <li>
               <%= link_to root_path,class: 'nav-link text-white' do %>
                <i class="fas fa-home"></i>
                トップ
                <% end %>
              </li>
              </div>
              <div class="col-3">
              <li>
                <%= link_to about_path,class: 'nav-link text-white' do %>
                  <i class="fas fa-exclamation-circle"></i>
                  About
                <% end %>
              </li>
              </div>
              <div class="col-3">
              <li>
                <% if user_signed_in? %>
                  <% if current_user.admin? %>
                    <%= link_to admin_users_path,class: 'nav-link text-white' do %>
                      <i class="fas fa-users"></i>
                      会員一覧（管理者用）
                    <% end %>
                  <% end %>
                <% end %>
              </li>
              </div>
            </ul>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>